kind: Service
apiVersion: v1
metadata:
  name: golang-demo
spec:
  type: LoadBalancer    
  selector:
    app: golang-demo
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 0
